config/routes.rb
Nupo::Application.routes.draw do

  root to: "home#index"
  resources :posters do
    post "update_url"
  end
  resources :widgets
  resources :tracks

  get "oauth/new" => "oauth#new"
  get "oauth/create" => "oauth#create"
  get "oauth/destroy" => "oauth#destroy"
  
  match ":url" => "posters#show"

end

app/models/poster.rb
class Poster < ActiveRecord::Base
  has_many :widgets
  
  validates_uniqueness_of :url, case_sensitive: false
  
  def verify(secret)
    secret == self.secret
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  belongs_to :poster
  
  def verify(secret)
    self.poster.verify(secret)
  end
end

app/models/widgets/image_widget.rb
class ImageWidget < Widget
end

app/models/widgets/link_widget.rb
class LinkWidget < Widget
end

app/models/widgets/location_widget.rb
class LocationWidget < Widget
end

app/models/widgets/music_widget.rb
class MusicWidget < Widget
end

app/models/widgets/share_widget.rb
class ShareWidget < Widget
end

app/models/widgets/text_widget.rb
class TextWidget < Widget
end

app/controllers/application_controller.rb
require 'soundcloud'
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  helper_method :connected?, :require_connected, :require_not_connected, :current_connection
  
  private
  def connected?
    (session[:access_token] && session[:access_token_secret])
  end
  
  def require_not_connected
    return false if connected?
  end
  
  def require_connected
    return false unless connected?
  end
  
  def current_connection
    return @connection if @connection
    return None unless connected?
    access_token = OAuth::AccessToken.new($sc_consumer, session[:access_token], session[:access_token_secret])
    @connection = Soundcloud.register({:access_token => access_token, :site => "http://api.#{$sc_host}"})
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: "home"
  end
end

app/controllers/oauth_controller.rb
# The two endpoints needed for OAuth authentication using the SoundCloud Ruby
# API wrapper.
#
# Note: $sc_consumer and $sc_host can be defined in your rails
# config/environment.rb file as follows:
#
# consumer_token = '[Your consumer token goes here]'
# consumer_secret = '[Your consumer secret goes here]'
# $sc_consumer = Soundcloud.consumer(consumer_token, consumer_secret "http://api.#{sc_host}")
# $sc_host = 'soundcloud.com' # could also be 'sandbox-soundcloud.com'
#
# (Your app is the "consumer" here and you can get your consumer token and 
#  consumer secret from your app's information page) 

class OauthController < ApplicationController
  before_filter :require_not_connected, only: [:new, :create]
  # Gets an oauth request token from SoundCloud and redirects the user to the
  # SoundCloud authorization page. The request token and secret are stored in
  # the session so they can be retrieved by the access_token endpoint.
  def new
    if session[:access_token] and session[:access_token_secret]
      redirect_to "/sc-connect-complete.html"
      return
    end
    
    callback_url = oauth_create_url
    request_token = $sc_consumer.get_request_token(:oauth_callback => callback_url)
    session[:request_token] = request_token.token
    session[:request_token_secret] = request_token.secret
    authorize_url = "http://#{$sc_host}/oauth/authorize?oauth_token=#{request_token.token}&display=popup"
    redirect_to authorize_url
  end

  # After authentication at the SoundCloud authorization page, the user is
  # redirected to this endpoint, which completes the authorization request.
  def create
    if params[:oauth_token] == session[:request_token]
      request_token = OAuth::RequestToken.new($sc_consumer,
      session[:request_token],
      session[:request_token_secret])
      access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
      
      sc = Soundcloud.register({:access_token => access_token, :site => "http://api.#{$sc_host}"})
      # Now you can use the sc object to access user data
      me = sc.User.find_me
      username = me.username
      # Save the access token so other controllers can use it
      session[:access_token] = access_token.token
      session[:access_token_secret] = access_token.secret
      # Request token is no longer needed
      session[:request_token] = session[:request_token_secret] = nil
    else
      logger.error 'ERROR: OauthController::access_token: authorization failed -' +
        'request token in session does not match token passed in params'
      username = ''
    end
    # Redirecting to sc-connect-compete.html closes the popup window and
    # invokes your js callback. Params appended to this url will be passed to
    # the callback
    redirect_to "/sc-connect-complete.html?username=#{CGI::escape(username)}"
  end
  
  # Log out
  def destroy
    session[:request_token] = nil
    session[:request_token_secret] = nil
    session[:oauth_token] = nil
    session[:access_token] = nil
    session[:access_token_secret] = nil
    # Note this doesn't actually disconnect them... yet
    redirect_to :back
  end

end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_filter :verify, only: [:edit, :update, :destroy, :update_url]
  def show
    @poster = Poster.find(params[:id]) if params[:id]
    @poster = Poster.find_by_url(params[:url]) if params[:url]
    redirect_to :root unless @poster
  end
  
  def new
    @poster = Poster.new(secret: SecureRandom.hex(10), url: SecureRandom.hex(5))
    until @poster.save
      @poster.url = SecureRandom.hex(5)
    end
    #theres obviously much better ways to do this
    #for example, represent the id in base64... with padding
    redirect_to edit_poster_url(@poster, secret: @poster.secret)
  end

  def edit
    @poster = Poster.find(params[:id])
  end

  def update
    @poster.update_attributes(params[:poster])
    render json: @poster.errors
  end
  
  def update_url
    if Poster.where(url: params[:poster][:url]).count == 0
      @poster.url = params[:poster][:url]
      @poster.save
      render json: @poster
    else
      render json: false, status: 500
    end
  end

  def destroy
    render json: @poster.destroy
  end
  
  private
  def verify
    @poster = Poster.find(params[:id])
    redirect_to :root unless @poster.secret == params[:secret]
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  def index
    sc = current_connection
    @tracks = sc.User.find_me.tracks
    render layout: nil
  end
  
  def show
    @id = params[:id]
    sc = current_connection
    @track = sc.Track.find(@id)
    render layout: nil
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_filter :verify, only: [:show, :update, :destroy]
  def index
    @poster = Poster.find(params[:poster_id])
    if @poster.verify(params[:secret])
      render json: @poster.widgets
    else
      render json: [], status: 500
    end
  end
  
  def show
    render json: @widget
  end
  
  def create
    @widget = Widget.new(params[:widget])
    @widget.poster = Poster.find(@widget.poster_id)
    
    if @widget.verify(params[:secret])
      @widget.type = params[:widget][:type]
      @widget.save
      @widget = Widget.find(@widget.id)
      render json: @widget
    else
      render nothing: true, status: 500
    end
  end

  def update
    @widget.update_attributes(params[:widget])
    render json: @widget
  end
  
  def destroy
    render json: @widget.destroy
  end
  
  private
  def verify
    secret = params[:secret]
    @widget = Widget.find(params[:id])
    render nothing: true unless @widget.verify(secret)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/home/index.html.erb
<section id="what">
<h1>What is Nupose?</h1>
<p>Nupose is a new way of making posters. Promote your band, gig or event with an interactive poster. Nupose makes it easy for people to share your event, listen ahead of time and find out where you're on</p>
</section>

<ul id="features" class="container_12">
  <li class="grid_4 prefix_2 alpha">
    <img src="/images/home/tracks.png">
    <h1>Your Tracks</h1>
    <p>Let people listen to what you'll play so they know they'll love it.</p>
  </li>
  <li class="grid_4 suffix_1 omega">
    <img src="/images/home/adjustable.png">
    <h1>It's Adjustable</h1>
    <p>You can edit your poster right here, in the browser, and from anywhere you want</p>
  </li>
  <li class="grid_4 prefix_2 alpha">
      <img src="/images/home/url.png">
      <h1>Choose your own URL</h1>
      <p>Make the url fit with your promotion</p>
  </li>
  <li class="grid_4 suffix_2 omega">
    <img src="/images/home/soundcloud.png">
    <h1>Connect to SoundCloud</h1>
    <p>And import any songs you've uploaded previously</p>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="no-js">
<head>
  <meta charset="utf-8">
  <!--[if IE]><![endif]--><%# do not remove; this actually has a purpose%>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Nupose</title>
  <meta name="description" content="Just listen, no hassles.">
  <meta name="author" content="Benjamin Taylor">
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  
  <!-- Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  
  <%= stylesheet_link_tag 'html5reset', '960', 'poster'%>

  <%= javascript_include_tag 'modernizr', 'prototype.s2.min', 'rails', 'application' %>
  
  <script src="http://connect.soundcloud.com/base.js"></script>
  
  <%= csrf_meta_tag %>
  
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  
  <%= yield :head %>
</head>
<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->

  <%= yield %>

  <script>
   var _gaq = [['_setAccount', 'UA-XXXXXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = '//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
</body>
</html>

app/views/layouts/home.html.erb
<!doctype html>
<html lang="en" class="no-js">
<head>
  <meta charset="utf-8">
  <!--[if IE]><![endif]--><%# do not remove; this actually has a purpose%>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Nupose</title>
  <meta name="description" content="Just listen, no hassles.">
  <meta name="author" content="Benjamin Taylor">
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  
  <!-- Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  
  <%= stylesheet_link_tag 'html5reset', '960', 'home' %>

  <%= javascript_include_tag 'modernizr', 'prototype.s2.min', 'rails', 'application' %>
  
  <%= csrf_meta_tag %>
  
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  
  <%= yield :head %>
</head>
<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->

  <header>
    <div id="branding" class="container_12">
      <h1>Nupose</h1>
    </div>
    <a id="new_poster" href="<%= new_poster_path %>">
      Make One
    </a>
  </header>
    
  <div id="content" class="container_12">
    <div id="flashes">
      <% if flash[:notice] %>
      <div class="flash">
        <div class="inner_glow"><%= flash[:notice] %></div>
      </div>
      <% elsif flash[:error] %>
      <div class="flash error">
        <div class="inner_glow"><%= flash[:error] %></div>
      </div>
      <% end %>
    </div><!-- /#flashes -->

    <%= yield %>
  </div><!-- /#content -->
  
  <footer>
    <p>Nupose was handcrafted by Ben Taylor.</p>
    <ul>
      <li>
        <a href="http://twitter.com/taybenlor">Twitter</a>
      </li>
      <li>
        <a href="http://taybenlor.com/">Blog</a>
      </li>
      <li>
        <a href="mailto:taybenlor@gmail.com">Email</a>
      </li>
    </ul>
  </footer>

  <script>
   var _gaq = [['_setAccount', 'UA-XXXXXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = '//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
</body>
</html>

app/views/posters/edit.html.erb
<header id="menu">
  <div class="branding container_12">
    <a href="/"><h1>Nupose</h1></a>
  </div>
  <div id="url" class="container_12">
    <h1>You'll be linking people to</h1>
    <label>http://nupose.com/</label>
    <input type="text" id="url_field" placeholder="<%= @poster.url %>">
    <button id="url_check" class="available">
      check
    </button>
  </div>
  <div id="connect">
    <% if connected? %>
      <a id="sc-connect" class="connected" href="/oauth/destroy">
        Disconnect
      </a>
    <% else %>
      <script>
      SC.Connect.options = {
        'request_token_endpoint': '/oauth/new',
        'access_token_endpoint': '/oauth/create',
        'callback': function(params) {
          sc_connected.apply(this, $A(arguments));
        }
      };
      </script>
      <a id="sc-connect"
         href="#" 
         onclick="SC.Connect.initiate();">
         Connect
      </a>
    <% end %>
  </div>
  <menu id="toolbar" class="container_12">
    <li id="text_tool" class="tool" data-widget="TextWidget">Text</li>
    <li id="image_tool" class="tool" data-widget="ImageWidget">Image</li>
    <li id="link_tool" class="tool" data-widget="LinkWidget">Link</li>
    <li id="music_tool" class="tool" data-widget="MusicWidget">Music</li>
    <li id="location_tool" class="tool" data-widget="LocationWidget">Location</li>
    <li id="share_tool" class="tool" data-widget="ShareWidget">Sharing</li>
  </menu>
</header>

<div id="left_bar" class="left bar">
  <h1>Background</h1>
  <label>Gradient</label>
  <input id="top_colour" type="color" class="color" value="<%# @poster.background_colour_top || "000000" %>"/>
  <input id="bottom_colour" type="color" class="color" value="<%# @poster.background_colour_bottom || "000000" %>"/>
  
  <h1>-or-</h1>
  <label>Image</label>
  <input type="text" placeholder="url" id="background_image">
</div>
<div id="canvas" class="container_12">
  <!-- touch me with your beautiful posters -->
</div>
<div id="right_bar" class="right bar">
  <button id="save">
    Save
  </button>
  <button id="preview">
    Preview
  </button>
  <button id="share_button" style="display: none">
    Share
  </button>
</div>

<%= javascript_include_tag 'create', 'jscolor' %>
<script>
load_poster(<%= @poster.to_json.html_safe %>);
</script>

app/views/posters/show.html.erb
<%= javascript_include_tag 'create' %>

<% if @poster.background_image && @poster.background_image != "" %>
<div id="poster" style="background: url('<%= @poster.background_image%>')">
<% else %>
<div id="poster" style="background: -webkit-gradient(linear, left bottom, left top, color-stop(1, #<%= @poster.background_colour_top %>),color-stop(0, #<%= @poster.background_colour_bottom %>))">
<% end %>
  <%= render partial: "widgets/widget", collection: @poster.widgets %>
</div>
<footer>
  <a href="/"><h1>Nupose</h1></a>
  <p>Made using <%= link_to "Nupose", root_url %> - the new way to make event posters.</p>
  <p>Nupose was handcrafted by <%= link_to "Ben Taylor", "http://taybenlor.com" %></p>
</footer>

app/views/tracks/_track.html.erb
<% track = @track || track %>
<div class="track">  
  <object height="81" width="100%"> <param name="movie" value="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= track.id %>"></param> <param name="allowscriptaccess" value="always"></param> <param name="wmode" value="opaque" /> <embed allowscriptaccess="always" height="81" src="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= track.id %>" type="application/x-shockwave-flash" width="100%"></embed> </object>
</div>

app/views/tracks/_track_summary.html.erb
<% track = track_summary %>
<li class="track_summary" data-track-id="<%= track.id %>">
<%= track.title %></a> by <a href="<%= track.user.permalink_url %>"><%= track.user.username %></a></span> 
</li>

app/views/tracks/index.html.erb
<h1>Select a Track</h1>
<ul class="tracks">
  <%= render partial: "track_summary", collection: @tracks %>
</ul>
<button>
  Use this Track
</button>

app/views/tracks/show.html.erb
<%= render partial: "track", object: @track %>

app/views/widgets/_image_widget.html.erb
<%# Image Widget 
One Style 
%>
<img src="<%= image_widget.url %>">

app/views/widgets/_link_widget.html.erb
<%# Text Widget
One Style
%>
<a href="<%= link_widget.url %>"><%= link_widget.text %></a>

app/views/widgets/_location_widget.html.erb
<%# Location Widget
 Two Styles
 1. Map
 2. Address + Link
 %>

app/views/widgets/_music_widget.html.erb
<%# Music Widget
One Style - Soundcloud
%>
  <object height="81" width="100%"> <param name="movie" value="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= music_widget.track_id %>"></param> <param name="allowscriptaccess" value="always"></param> <param name="wmode" value="opaque" /> <embed allowscriptaccess="always" height="81" src="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= music_widget.track_id %>" type="application/x-shockwave-flash" width="100%"></embed> </object>

app/views/widgets/_share_widget.html.erb
<%# Share Widget
Two Styles:
1. Big
2. Small
%>
<a name="fb_share"></a>
<div style="margin: 10px"></div>
<a href="http://twitter.com/share" data-count="none" class="twitter-share-button">Tweet</a>

<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share"></script>
<script src="http://platform.twitter.com/widgets.js"></script>

app/views/widgets/_text_widget.html.erb
<%# Text Widget
One Style
%>
<h1><%= text_widget.text %></h1>

app/views/widgets/_widget.html.erb
<% widget = @widget unless widget %>
<div class="widget" style="<%= widget.style %>">
  <%= render partial: "/widgets/" + widget.class.name.underscore, object: widget %>
</div>